### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by Matrix-Zhang** [nemequ/vala-extra-vapis#25]
1)build docs fail:

Running Sphinx v1.2.3
loading pickled environment... not yet created

Theme error:
no theme named 'sphinx_rtd_theme' found (missing theme.conf?)

Waf: Leaving directory `/opt/projects/valum/build'
Build failed
 -> task in 'app' failed (exit status 1): 
	{task 140638660706192: valac app.vala -> app.c}
''
 -> task in 'app' failed (exit status 1): 
	{task 140638660769040: valac app.vala -> app.c}
''
 -> task in '' failed (exit status 1): 
	{task 140638660703632: ${SPHINXBUILD} -b html ../docs docs gnu-lgpl-v3.0.rst,application.rst,ctpl.rst,getting-started.rst,hacking.rst,index.rst,installation.rst,module.rst,configuration.rst,index.rst,json.rst,persistence.rst,scripting.rst,static-resource.rst,redirection-and-error.rst,route.rst,router.rst,connection.rst,converters.rst,cookies.rst,filters.rst,index.rst,request.rst,response.rst,cgi.rst,fastcgi.rst,index.rst,scgi.rst,soup.rst -> }
' /usr/bin/sphinx-build -b html ../docs docs '

2)build example fail:

In file included from examples/markdown/app.c:7:0:
/opt/projects/valum/build/static/valum.h:15:17: fatal error: gee.h: no such file or directory

**Comment by nemequ** [comment]
I think you filed this in the wrong repository.

That said, it sounds like you don't have the development package for libgee installed, or you didn't include the necessary cflags in your build system.
