### ISSUE TITLE
bindings for shapelib

### ISSUE THREAD

**Issue by ibinshoid** [nemequ/vala-extra-vapis#51]
I've made a vapi for shapelib (http://shapelib.maptools.org/).
It works for me but brings warnings at compilation.
Can you help me make it better, please?
If it's good enough you can publish it on the repository.

[shapelib-vapi.zip](https://github.com/nemequ/vala-extra-vapis/files/981578/shapelib-vapi.zip)

**Comment by arteymix** [comment]
@ibinshoid 

Is it possible to paste the VAPI somewhere safe? Like a [gist](https://gist.github.com/) or via [Fedora Paste](https://paste.fedoraproject.org/)?

**Comment by ibinshoid** [comment]
I've made a gist here: https://gist.github.com/ibinshoid/86d36472b9211c8de71359bffa10583c
I didn't know there is something like gist in github. Thank you for the hint.

**Comment by arteymix** [comment]
Few things first:

 - you only need to put `cheader_filename` at the namespace level
 - weak is deprecated in favour of unowned (same semantics)
 - all the CreateObject-like functions could become class constructors

**Comment by ibinshoid** [comment]
next try, now with test program:
https://gist.github.com/ibinshoid/86d36472b9211c8de71359bffa10583c
Its only for the dbf part, i have no experience with shp files jet.

**Comment by arteymix** [comment]
Ok figured it out! Classes in Vala are always refered by address, so the generated code produced `DBFHandle*` instead of `DBFHandle`. This can be easily fixed by using `DBFInfo` instead.

**Comment by arteymix** [comment]
You could use `DBFClose` as a free function if you want automatic cleanups.

**Comment by arteymix** [comment]
I didn't know for `[NoArrayLength]`.. did you meant `[CCode (array_length = false)]`?

**Comment by nemequ** [comment]
`[NoArrayLength]` is the old-fashioned way to say `[CCode (array_length = false)]`, but it applies to entire methods (instead of single arguments).  IIRC it was replaced around 0.8.  I'm pretty sure we were emitting deprecation warnings for a while, but maybe the code was just removed completely.

**Comment by ibinshoid** [comment]
Ok,
DBFInfo instead of DBFHandle removes all warnings. Great.
DBFClose doesn't free anything, just closes the filestream. Using it as free function makes a segmentation fault.
Changed [NoArrayLength] to [CCode (array_length = false)].

Thank you for the help.

**Comment by nemequ** [comment]
@ibinshoid, was the VAPI really generated by vapigen as the first line of the file says?  If not, please remove that line.  Once that's clarified I'll add this to the repo.

Usually for Vala bindings we like to convert fields and methods (but not types) from camelCase to lowercase_with_underscores, and attach a `[CCode (cname = "…")]` annotation to get the correct generated code.  vala-extra-vapis has a lower barrier for entry than vala, though, so it won't prevent inclusion if you don't want to convert them.

**Comment by ibinshoid** [comment]
Ok
i've used vapigen to get a first vapi but its much different now, so i removed the first line.

Also i have changed all method names to lowercase_with_underscores.
i hope its good.

**Comment by arteymix** [comment]
@ibinshoid Could you open a pull-request with your work so that we can review it before final inclusion?

**Comment by ibinshoid** [comment]
I'm not very firm with git.
"New pull request" on github.com ask for a branch, but when i create a local branch and try to push it i get a "Permission to nemequ/vala-extra-vapis.git denied to ibinshoid".
Please help me how to open a pull-request.

**Comment by nemequ** [comment]
@ibinshoid if you just want to be done with this I can do the rest for you.  However, if you want to learn…

First, you'll need to create a fork; there is a "Fork" button in the top-right corner of the page, click it and follow directions.  Once you have a fork you need to push its repository on github; based on what you wrote in your last comment it sounds like you've already figured that part out… you'll have full access to your fork, so when you try to push to it you shouldn't see that permission denied error.

For actually creating the PR, [GitHub's documentation](https://help.github.com/articles/creating-a-pull-request/) is pretty decent.

**Comment by ibinshoid** [comment]
Worked.
Thank you for the help.
