### ISSUE TITLE
Archive this repository?

### ISSUE THREAD

**Issue by astavale** [nemequ/vala-extra-vapis#63]
GitHub allows [a repository to be archived](https://help.github.com/articles/archiving-repositories/). It is then read-only so links to it will still work, but the active repository, https://gitlab.gnome.org/GNOME/vala-extra-vapis, would then be easier to maintain. Changing the description to point to the new repository would also be helpful, e.g. "Moved to https://gitlab.gnome.org/GNOME/vala-extra-vapis"

**Comment by arteymix** [comment]
Does GNOME's GitLab require a registered account?

**Comment by astavale** [comment]
They have to have a registered account, but they can use their existing GitHub, GitLab.com or Google account. They don't need a full GNOME Developer account with SSH keys. They have to create their own fork of a project on GNOME's GitLab to create a merge request. That doesn't need a full GNOME Developer account.
 * https://gitlab.gnome.org/users/sign_in?redirect_to_referer=yes
 * https://wiki.gnome.org/GitLab

**Comment by arteymix** [comment]
In that case, it would be fine to archive this and refer contributors upstream. However, that would be up to @nemequ.

**Comment by nemequ** [comment]
It's not really accurate to say that the one on GNOME's infrastructure is the "active" repository.  They're both active.

Anyways, it's probably not a bad idea to deactivate this one now that GNOME's infrastructure is easier to use, though.  Some people have been committing to one repo without syncing the other one (it's happened in both directions), and just using a single repo would fix that.  I don't have any problems with dropping this repo; I'll go ahead and make the changes.
